license-key: "XXXX-XXXX-XXXX-XXXX"
lang-file: "EN.yml"

updates:
  join-notify-delay-seconds: 5
  periodic-broadcast:
    enabled: true
    interval-minutes: 30

bot:
  name: "MinecraftBot"
  default-totem-count: -1
  max-totem-normal: 37
  max-totem-event: 74
  blocked-worlds:
    - "world_nether"
    - "world_the_end"

  event:
    range: 32

  ally:
    range: 16
    pre-range: 32
    return-teleport-distance: 12
    return-teleport-cooldown-ms: 1000

  team-ally:
    range: 16
    pre-range: 32
    return-teleport-distance: 12
    return-teleport-cooldown-ms: 1000
