name: MinecraftBot
version: '1.0.6'
main: com.monkey.mcbot.MinecraftBot
api-version: '1.21'
folia-supported: true
authors: [ MonkeyMoon104 ]
description: Minecraft bot plugin
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - WorldGuard

commands:
  bot:
    description: Open the normal bot settings GUI
    permission: mcb.bot.use
  botevent:
    description: Open the event bot settings GUI
    permission: admin.host.bot
  botally:
    description: Open the ally bot settings GUI
    permission: mcb.bot.use
  botteamally:
    description: Create and manage a team ally bot
    permission: mcb.bot.use
  mcbreload:
    description: Reload configuration or remove bots/maps
    usage: /mcbreload <config|bot|maps|all>
    permission: mcb.admin.use

permissions:
  mcb.admin.use:
    description: Allows using the mcbreload command
    default: op
  mcb.bot.use:
    description: Allows using the bot, botally and botteamally commands
    default: true
  admin.host.bot:
    description: Allows creating an event bot
    default: op
