name: MinecraftBot
version: '1.0.6'
main: com.monkey.mcbot.MinecraftBot
api-version: '1.21'
folia-supported: true
authors: [ MonkeyMoon104 ]
description: Minecraft bot plugin
softdepend:
  - PlaceholderAPI
  - LuckPerms
loadbefore:
  - WorldGuard

commands:
  bot:
    description: Apri la GUI delle impostazioni del bot normale
    permission: mcb.bot.use
  botevent:
    description: Apri la GUI delle impostazioni del bot evento
    permission: admin.host.bot
  botally:
    description: Apri la GUI delle impostazioni del bot ally
    permission: mcb.bot.use
  botteamally:
    description: Crea e gestisce un bot team ally
    permission: mcb.bot.use
  mcbreload:
    description: Ricarica la configurazione o rimuovi bot/mappe
    usage: /mcbreload <config|bot|maps|all>
    permission: mcb.admin.use

permissions:
  mcb.admin.use:
    description: Permette di usare il comando mcbreload
    default: op
  mcb.bot.use:
    description: Permette di usare i comandi bot, botally e botteamally
    default: true
  admin.host.bot:
    description: Permette di creare un bot evento
    default: op
