org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.workers.max=8
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.warning.mode=summary
mcbot.version=1.2.0
