pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://repo.papermc.io/repository/maven-public/" }
        maven { url = "https://repo.monkeymoon104.it/releases" }
    }
}

rootProject.name = 'MinecraftBot'

include 'mcbot-api'
include 'mcbot-core'

include 'versions:v1_21_4'
include 'versions:v1_21_5'
include 'versions:v1_21_6'
include 'versions:v1_21_7'
include 'versions:v1_21_8'
include 'versions:v1_21_9'
include 'versions:v1_21_10'
include 'versions:v1_21_11'

include 'plugin'
