messages:
  set-type: "Set type = %type%"
  set-follow: "Set follow = %type%"
  spawn-bot: "&aBot spawned with selected armor!"
  follow-toggle-name: "&bToggle Follow"
  dead-bot-msg: "&aYou have killed the bot!"
  despawn-bot: "&cBot despawned!"

bot:
  name: "CrystalBot"
  totem-finish: "[%botname%] Running out of totems"
  default-totem-count: -1

gui:
  default-armor:
    helmet: NETHERITE
    chestplate: NETHERITE
    leggings: NETHERITE
    boots: NETHERITE
    no-armor: BARRIER
  follow-button:
    name: "&bToggle Follow"
    material: "LEAD"
  spawn-button:
    name: "&aSpawn Bot"
    material: "SPAWNER"
  despawn-button:
    name: "&cDespawn Bot"
    material: "BARRIER"
  save-button:
    name: "&aSave Changes"
    material: "GREEN_WOOL"