name: sandbox-training
version: '1.0.0'
main: it.coralmc.sandbox.SandboxTraining
api-version: '1.21'
authors: [ MonkeyMoon104 ]
description: Sandbox bot plugin

commands:
  bot:
    description: Open bot settings GUI
    permission: sb.bot.use
  sbreload:
    description: Ricarica la configurazione o rimuovi bot/mappe
    usage: /sbreload <config|bot|maps|all>
    permission: sb.admin.use

  permissions:
    sb.admin.use:
      description: Permette di usare il comando sbreload
      default: op
    sb.bot.use:
      description: Permette di usare il comando bot
      default: true