name: sandbox-training
version: '1.0.0'
main: it.coralmc.sandbox.SandboxTraining
api-version: '1.21'
authors: [ MonkeyMoon104 ]
description: Sanbox bot plugin

commands:
  bot:
    description: Open bot settings GUI