import io.papermc.paperweight.userdev.ReobfArtifactConfiguration

apply plugin: 'io.papermc.paperweight.userdev'

paperweight {
    reobfArtifactConfiguration = ReobfArtifactConfiguration.getREOBF_PRODUCTION()
}

dependencies {
    implementation project(':mcbot-api')
    paperweight.paperDevBundle("1.21.4-R0.1-SNAPSHOT")

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    implementation "xyz.xenondevs.invui:invui:1.49"
    compileOnly 'me.clip:placeholderapi:2.12.2'
    compileOnly 'com.github.sirblobman.api:core:2.9-SNAPSHOT'
    compileOnly 'com.github.sirblobman.combatlogx:api:11.6-SNAPSHOT'
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
