apply plugin: 'com.gradleup.shadow'

dependencies {
    implementation project(':core')
    implementation project(path: ':versions:v1_21_4', configuration: 'reobf')
    implementation project(path: ':versions:v1_21_5', configuration: 'reobf')
    implementation project(path: ':versions:v1_21_6', configuration: 'reobf')
    implementation project(path: ':versions:v1_21_7', configuration: 'reobf')
    implementation project(path: ':versions:v1_21_8', configuration: 'reobf')
    implementation project(path: ':versions:v1_21_9', configuration: 'reobf')
    implementation project(path: ':versions:v1_21_10', configuration: 'reobf')
    implementation project(path: ':versions:v1_21_11', configuration: 'reobf')
}

shadowJar {
    archiveBaseName.set('MinecraftBot')
    archiveVersion.set('')
    archiveClassifier.set('')
    mergeServiceFiles()
}

build.dependsOn shadowJar