name: sandbox-training
version: '1.0.0'
main: com.monkey.mcbot.MinecraftBot
api-version: '1.21'
authors: [ MonkeyMoon104 ]
description: Sandbox bot plugin
depend:
  - PlaceholderAPI

commands:
  bot:
    description: Apri la GUI delle impostazioni del bot normale
    permission: sb.bot.use
  botevent:
    description: Apri la GUI delle impostazioni del bot evento
    permission: admin.host.bot
  sbreload:
    description: Ricarica la configurazione o rimuovi bot/mappe
    usage: /sbreload <config|bot|maps|all>
    permission: sb.admin.use

  permissions:
    sb.admin.use:
      description: Permette di usare il comando sbreload
      default: op
    sb.bot.use:
      description: Permette di usare il comando bot
      default: true
    admin.host.bot:
      description: Permette di creare un bot evento
      default: op