import io.papermc.paperweight.userdev.ReobfArtifactConfiguration

apply plugin: 'io.papermc.paperweight.userdev'

paperweight {
    reobfArtifactConfiguration = ReobfArtifactConfiguration.getREOBF_PRODUCTION()
}

def libsCatalog = extensions.getByType(org.gradle.api.artifacts.VersionCatalogsExtension).named('libs')

dependencies {
    paperweight.paperDevBundle(libsCatalog.findVersion('paper-bundle-1_21_6').get().requiredVersion)
    compileOnly project(':mcbot-core')
}
