import io.papermc.paperweight.userdev.ReobfArtifactConfiguration

apply plugin: 'io.papermc.paperweight.userdev'

paperweight {
    reobfArtifactConfiguration = ReobfArtifactConfiguration.getREOBF_PRODUCTION()
}

dependencies {
    paperweight.paperDevBundle("1.21.6-R0.1-SNAPSHOT")
    compileOnly project(':mcbot-core')
}