name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Extract version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Publish to MonkeyRepo
        env:
          ORG_GRADLE_PROJECT_monkeyrepo.user: ${{ secrets.MONKEYREPO_USER }}
          ORG_GRADLE_PROJECT_monkeyrepo.secret: ${{ secrets.MONKEYREPO_SECRET }}
        run: ./gradlew publish --no-daemon
